config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :accounts

  resources :accounts, only: %i() do
    scope module: :accounts do
      resources :account_emails, only: %i(index), path: :emails
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :confirmable, :database_authenticatable, :lockable,
         :recoverable, :registerable, :rememberable, :validatable

  has_many :account_emails

  def confirm(args = {})
    transaction do
      super.tap do |res|
        account_emails.create!(email: email) if res
      end
    end
  end
end

app/models/account_email.rb
class AccountEmail < ActiveRecord::Base
end

app/controllers/accounts/account_emails_controller.rb
module Accounts
  class AccountEmailsController < ApplicationController
    add_views_path :account_emails

    def index
      @emails = AccountEmail.where(account_id: params[:account_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/account_emails/index.html.slim
ul
  - @emails.each do |email|
    li
      = "Email: #{email.email}, created_at: #{email.created_at}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackendChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>
  Welcome to the Babbel backend challenge.
</h2>

<%= link_to 'Logout', destroy_account_session_path, method: :delete %>